New feature `use asdf current` to activate current plugins.
In your `.envrc` file now you can do: `use asdf current`.
And it will load the same plugins and versions as listed by
the output of `asdf current`.

Notice that `use asdf current` is a bit slow since it will
try to determine the version for each installed plugin
(same thing that `asdf current` does). But, the upside is
that you will have not only local plugins active but also
those in global ~/.tool-versions file (as resolved by asdf).

This means `use asdf current` will also activate plugins
that use legacy files and thus are not present inside
`.tool-versions`. (this was a limitation of `use asdf local`)

The old behaviour is now named `use asdf local` and is
currently still the default if you give no args to `use asdf`.
This is because `use asdf current` is slower, and I'm not
sure all people would like that by default.

TODO:

- [ ] Add lots of BATS test.
- [ ] Decide if `use asdf global` becomes default.
- [ ] Improve docs.

Alternative implementation for #12.
Fixes #13

diff --git a/shims/direnv_use_asdf b/shims/direnv_use_asdf
--- a/shims/direnv_use_asdf
+++ b/shims/direnv_use_asdf
@@ -15,9 +15,15 @@
 # limitations under the License.
 #
 
+# Load asdf util functions if not already loaded
 if [ -z "$(declare -f -F with_plugin_env)" ]; then
   # shellcheck disable=SC1090 # Can't follow non-constant source. Use a directive to specify location.
   source "$ASDF_DIR/lib/utils.sh"
+fi
+
+# Load direnv stdlib if not already loaded
+if [ -z "$(declare -f -F watch_file)" ]; then
+  eval "$(asdf exec direnv stdlib)"
 fi
 
 ## Usage: use_asdf [...]
@@ -28,24 +34,27 @@ fi
 # Otherwise two argments are expected, a plugin name and version.
 # If no arguments are given, a .tool-versions file will be looked up.
 use_asdf() {
-  local plugin
-  local version
-  if [ -z "$*" ]; then
-    local tool_versions
-    tool_versions="$(find_up .tool-versions)"
-    if [ -f "$tool_versions" ]; then
-      use asdf "$tool_versions"
-    else
-      log_error "could not find .tool-versions file"
-      return 1
-    fi
+  if [ -z "$*" ] || [ "local" == "$*" ]; then
+    use_asdf "$(_local_versions_file)"
+
+  elif [ "current" == "$*" ]; then
+    eval "$(_load_current_plugins_env "$(_local_versions_file)")"
+
   elif [ -f "$1" ]; then
-    _load_plugins_env "$1"
-  elif [ -n "$1" ]; then
+    eval "$(_load_local_plugins_env "$1")"
+
+  elif [ -n "$1" ] && [ -z "$2" ]; then
     if ! (check_if_plugin_exists "$1"); then
       return 1
     fi
-    _load_plugin_env "$1" "$2"
+    eval "$(_load_plugin_version_and_file "$1")"
+
+  elif [ -n "$1" ] && [ -n "$2" ]; then
+    if ! (check_if_version_exists "$1" "$2"); then
+      return 1
+    fi
+    eval "$(_plugin_env_bash "$1" "$2")"
+
   else
     log_error "Invalid args for use asdf. Usage:"
     log_error "   use asdf TOOL_VERSIONS_FILE"
@@ -55,41 +64,84 @@ use_asdf() {
 }
 
 _xargs_par() {
-  xargs -n 1 -P "$(getconf _NPROCESSORS_ONLN)" "$@"
+  xargs -P "$(getconf _NPROCESSORS_ONLN)" "$@"
+}
+
+_pardo() {
+  local this_file="${BASH_SOURCE[0]}"
+  _xargs_par -n 1 "$this_file" 'do' "$@"
+}
+
+_local_versions_file() {
+  local tool_versions
+  tool_versions="$(find_up .tool-versions)"
+  if [ -f "$tool_versions" ]; then
+    echo "$tool_versions"
+  else
+    log_error "could not find .tool-versions file"
+    return 1
+  fi
 }
 
 _plugins_in_file() {
   local tool_versions=$1
-  cut -d'#' -f1 "$tool_versions" | cut -d' ' -f1 | awk NF
+  cut -d'#' -f1 "$tool_versions" | cut -d' ' -f1 | awk NF | uniq
 }
 
-_load_plugin_env() {
-  eval "$(_plugin_env_bash "$1" "$2")"
+_all_plugins_list() {
+  find "$(get_plugin_path)" -maxdepth 1 -mindepth 1 -exec basename '{}' \;
 }
 
-_load_plugins_env() {
+_load_current_plugins_env() {
+  _sort_all_plugins_list "$@" | _pardo _load_plugin_version_and_file
+}
+
+_sort_all_plugins_list() {
   local tool_versions=$1
-  local this_file="${BASH_SOURCE[0]}" #needs to before watch_file !
-  watch_file "$tool_versions"
-  eval "$(_plugins_in_file "$tool_versions" | _xargs_par "$this_file" 'do' _plugin_env_bash)"
+  local tmp_local_plugin_names
+  tmp_local_plugin_names="$(mktemp)"
+  _plugins_in_file "$tool_versions" | tee "$tmp_local_plugin_names"
+  _all_plugins_list | grep -v -F -f "$tmp_local_plugin_names"
+  rm "$tmp_local_plugin_names"
+}
+
+_load_local_plugins_env() {
+  local tool_versions=$1
+  _plugins_in_file "$tool_versions" | _pardo _load_plugin_version_and_file
 }
 
 _plugin_env() {
-  direnv dotenv bash <(env)
+  asdf exec direnv dotenv bash <(env)
+}
+
+# from asdf plugin_current_command
+_load_plugin_version_and_file() {
+  local plugin_name=$1
+  local versions_and_path
+  versions_and_path="$(find_versions "$plugin_name" "$(pwd)")"
+  if test -z "$versions_and_path"; then
+    return 0
+  fi
+
+  local path
+  path=$(cut -d '|' -f 2 <<<"$versions_and_path")
+  IFS=$'\n' read -r -a versions <<<"$(cut -d '|' -f 1 <<<"$versions_and_path" | uniq)"
+  for version in "${versions[@]}"; do
+    echo use_asdf "$plugin_name" "$version"
+  done
+  if [ -f "$path" ]; then
+    echo watch_file "$path"
+  fi
 }
 
 _plugin_env_bash() {
-  local plugin=$1
-  local version
+  local plugin="${1}"
+  local version="${2}"
   local old_path="$PATH"
-  version="${2:-$(get_preset_version_for "$plugin")}"
-  if [ -z "$version" ]; then
-    log_error "asdf: could not find current version for $plugin" >&2
-    return 1
+  if [ -n "$version" ]; then
+    echo "log_status using asdf $plugin $version"
+    with_plugin_env "$plugin" "$version" _plugin_env | sed "s#:$old_path#:'\"\$PATH\"'#"
   fi
-
-  echo "log_status using asdf $plugin $version"
-  with_plugin_env "$plugin" "$version" _plugin_env | sed "s#:$old_path#:'\"\$PATH\"'#"
 }
 
 if [ "do" == "$1" ]; then
