Support reading legacy files version

diff --git a/shims/direnv_use_asdf b/shims/direnv_use_asdf
--- a/shims/direnv_use_asdf
+++ b/shims/direnv_use_asdf
@@ -11,7 +11,14 @@ use_asdf() {
   local plugin
   local version
   if [ -z "$*" ]; then
-    use asdf "$(find_up .tool-versions)"
+    local tool_versions
+    tool_versions="$(find_up .tool-versions)"
+    if [ -f "$tool_versions" ]; then
+      use asdf "$tool_versions"
+    else
+      echo "direnv: could not find .tool-versions file" >&2
+      return 1
+    fi
   elif [ -f "$1" ]; then
     local tool_versions="$1"
     watch_file "$tool_versions"
@@ -20,34 +27,47 @@ use_asdf() {
     for plugin_and_version in $(cut -d'#' -f1 "$tool_versions" | awk NF | tail -r); do
       IFS=$' ' read -r plugin version <<< "$plugin_and_version"
       echo "direnv: using asdf $plugin $version"
-      direnv_load _asdf_plugin_dump_env "$plugin" "$version"
+      direnv_load _direnv_asdf_dump_env "$plugin" "$version"
     done
-  elif [ -n "$1" ] && [ -n "$2" ]; then
+  elif [ -n "$1" ]; then
     plugin="$1"
-    version="$2"
+    version="${2:-$(_direnv_asdf_preset_version "$plugin")}"
+    if [ -z "$version" ]; then
+      echo "asdf: could not find current version for $plugin" >&2
+      return 1
+    fi
     echo "direnv: using asdf $plugin $version"
-    direnv_load _asdf_plugin_dump_env "$1" "$2"
+    direnv_load _direnv_asdf_dump_env "$1" "$2"
   else
-    echo "direnv: Invalid args: use asdf $*"   >&2
-    echo "        use asdf TOOL_VERSIONS_FILE" >&2
-    echo "        use asdf TOOL_NAME VERSION"  >&2
+    echo "direnv: Invalid args: use asdf $*"     >&2
+    echo "        use asdf TOOL_VERSIONS_FILE"   >&2
+    echo "        use asdf TOOL_NAME [VERSION]"  >&2
     return 1
   fi
 }
 
 # asdf helper: create this wrapper since asdf expects a function callback
-_asdf_direnv_dump() {
+_direnv_asdf_dump() {
   direnv dump
 }
 
+# asdf helper: get a tool version
+_direnv_asdf_preset_version() {
+  local plugin=$1
+  ( # use a sub-shell since asdf introduces set -e
+    # shellcheck disable=SC1090 # Can't follow non-constant source. Use a directive to specify location.
+    source "$ASDF_DIR/lib/utils.sh"
+    get_preset_version_for "$plugin"
+  )
+}
+
 # asdf helper: dump the environment needed for plugin and version
-_asdf_plugin_dump_env() {
+_direnv_asdf_dump_env() {
   local plugin=$1
   local version=$2
   ( # use a sub-shell since asdf introduces set -e
     # shellcheck disable=SC1090 # Can't follow non-constant source. Use a directive to specify location.
     source "$ASDF_DIR/lib/utils.sh"
-    with_plugin_env "$plugin" "$version" _asdf_direnv_dump
+    with_plugin_env "$plugin" "$version" _direnv_asdf_dump
   )
 }
-
