Use xargs -P to dump plugin environment in parallel (#7)
Max num of procs will be the number of online processors.

diff --git a/shims/direnv_use_asdf b/shims/direnv_use_asdf
--- a/shims/direnv_use_asdf
+++ b/shims/direnv_use_asdf
@@ -15,6 +15,11 @@
 # limitations under the License.
 #
 
+if [ -z "$(declare -f -F with_plugin_env)" ]; then
+  # shellcheck disable=SC1090 # Can't follow non-constant source. Use a directive to specify location.
+  source "$ASDF_DIR/lib/utils.sh"
+fi
+
 ## Usage: use_asdf [...]
 #
 # Loads environment variables from `asdf` current tools.
@@ -31,60 +36,65 @@ use_asdf() {
     if [ -f "$tool_versions" ]; then
       use asdf "$tool_versions"
     else
-      echo "direnv: could not find .tool-versions file" >&2
+      log_error "could not find .tool-versions file" >&2
       return 1
     fi
   elif [ -f "$1" ]; then
-    local tool_versions="$1"
-    watch_file "$tool_versions"
-    local IFS
-    IFS=$'\n'
-    for plugin_and_version in $(cut -d'#' -f1 "$tool_versions" | awk NF | tail -r); do
-      IFS=$' ' read -r plugin version <<<"$plugin_and_version"
-      echo "direnv: using asdf $plugin $version"
-      direnv_load _direnv_asdf_dump_env "$plugin" "$version"
-    done
+    _load_plugins_env "$1"
   elif [ -n "$1" ]; then
-    plugin="$1"
-    version="${2:-$(_direnv_asdf_preset_version "$plugin")}"
-    if [ -z "$version" ]; then
-      echo "asdf: could not find current version for $plugin" >&2
+    if ! (check_if_plugin_exists "$1"); then
       return 1
     fi
-    echo "direnv: using asdf $plugin $version"
-    direnv_load _direnv_asdf_dump_env "$1" "$2"
+    _load_plugin_env "$1" "$2"
   else
-    echo "direnv: Invalid args: use asdf $*" >&2
-    echo "        use asdf TOOL_VERSIONS_FILE" >&2
-    echo "        use asdf TOOL_NAME [VERSION]" >&2
+    log_error "Invalid args for use asdf. Usage:"
+    log_error "   use asdf TOOL_VERSIONS_FILE"
+    log_error "   use asdf TOOL_NAME [VERSION]"
     return 1
   fi
 }
 
-# asdf helper: create this wrapper since asdf expects a function callback
-_direnv_asdf_dump() {
-  direnv dump
+_xargs_par() {
+  xargs -n 1 -P "$(getconf _NPROCESSORS_ONLN)" "$@"
 }
 
-# asdf helper: get a tool version
-_direnv_asdf_preset_version() {
-  local plugin=$1
-  (
-    # use a sub-shell since asdf introduces set -e
-    # shellcheck disable=SC1090 # Can't follow non-constant source. Use a directive to specify location.
-    source "$ASDF_DIR/lib/utils.sh"
-    get_preset_version_for "$plugin"
-  )
+_plugins_in_file() {
+  local tool_versions=$1
+  cut -d'#' -f1 "$tool_versions" | cut -d' ' -f1 | awk NF
 }
 
-# asdf helper: dump the environment needed for plugin and version
-_direnv_asdf_dump_env() {
-  local plugin=$1
-  local version=$2
-  (
-    # use a sub-shell since asdf introduces set -e
-    # shellcheck disable=SC1090 # Can't follow non-constant source. Use a directive to specify location.
-    source "$ASDF_DIR/lib/utils.sh"
-    with_plugin_env "$plugin" "$version" _direnv_asdf_dump
-  )
+_load_plugin_env() {
+  eval "$(_plugin_env_bash "$1" "$2")"
 }
+
+_load_plugins_env() {
+  local tool_versions=$1
+  watch_file "$tool_versions"
+  eval "$(_plugins_in_file "$tool_versions" | _xargs_par direnv_use_asdf 'do' _plugin_env_bash)"
+}
+
+_plugin_env_bash() {
+  local plugin=$1
+  local version
+  local old_path="$PATH"
+  version="${2:-$(get_preset_version_for "$plugin")}"
+  if [ -z "$version" ]; then
+    log_error "asdf: could not find current version for $plugin" >&2
+    return 1
+  fi
+
+  _plugin_env() {
+    echo "log_status using asdf $plugin $version"
+    direnv dotenv bash <(
+      env | grep -v '^PATH='
+      # shellcheck disable=SC2016 # Expressions dont expand in single quotes
+      echo "PATH=$PATH"':$PATH' | sed "s#:$old_path##"
+    )
+  }
+
+  with_plugin_env "$plugin" "$version" _plugin_env
+}
+
+if [ "do" == "$1" ]; then
+  eval "${@:2}"
+fi
